### PR TITLE
create,update,delete,show list course

### PR DESCRIPTION
**Pull request by luongvanlinh**

### CODE REVIEW

**Comment by luongvanlinh** [comment]
https://edu-redmine.sun-asterisk.vn/issues/37970
https://edu-redmine.sun-asterisk.vn/issues/37971
https://edu-redmine.sun-asterisk.vn/issues/37972
https://edu-redmine.sun-asterisk.vn/issues/38138

**Comment by luongvanlinh** [comment]
Screenshot from 2021-07-08 23-12-48
Screenshot from 2021-07-08 23-15-26
Screenshot from 2021-07-08 23-15-49

**Review by hoanq-2556 — APPROVED** [review]

**Comment by luongvanlinh** [comment]
ready

**Comment by vanvtt-0952** [comment]
commented 
KHÔNG REVIEW

**Pull request closed without merging**
